# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.17.0
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: install
          command: npm ci
      - run:
          name: authenticate
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - run:
          name: semantic
          command: npx semantic-release
      - run:
          name: Merge to develop
          command: git fetch && git pull
      - run:
          name: checkout develop
          command: git checkout develop
      - run:
          name: Merge master
          command: git merge master
      - run:
          name: push
          command: git push
workflows:
  version: 2
  build-deploy-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
